version: 2.1

executors:
  python-executor:
    docker:
      - image: circleci/python:3.10
    working_directory: ~/repo
  node-executor:
    docker:
      - image: circleci/node:14
    working_directory: ~/repo

jobs:
  backend-test:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            cd backend
            rm -rf venv
            python -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt
      # - run:
      #     name: List Installed Packages
      #     command: |
      #       . venv/bin/activate
      #       pip list
      - run:
          name: Set DJANGO_SETTINGS_MODULE
          command: |
            echo "export DJANGO_SETTINGS_MODULE=config.settings" >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: Run Tests
          command: |
            pytest --maxfail=5 --disable-warnings

  frontend-test:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Navigate to frontend directory
          command: cd frontend
      - run:
          name: Clear NPM Cache
          command: npm cache clean --force
      - run:
          name: Install Node.js dependencies
          command: npm install
      - run:
          name: Run React tests
          command: npm test -- --watchAll=false --detectOpenHandles

workflows:
  version: 2.1
  build-and-test:
    jobs:
      - backend-test
      - frontend-test
