version: 2.1

executors:
  python-executor:
    docker:
      - image: circleci/python:3.9
    working_directory: ~/repo
  node-executor:
    docker:
      - image: circleci/node:14
    working_directory: ~/repo

jobs:
  backend-test:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Install Python dependencies
          command: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
      - run:
          name: Run Django tests
          command: python manage.py test

  frontend-test:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: List files in working directory
          command: ls -la
      - run:
          name: Verify package.json existence
          command: |
            if [ ! -f package.json ]; then
              echo "package.json not found in $(pwd)"
              exit 1
            fi
      - run:
          name: Install Node.js dependencies
          command: npm install
      - run:
          name: Run React tests
          command: npm test -- --watchAll=false

workflows:
  version: 2.1
  build-and-test:
    jobs:
      - backend-test
      - frontend-test
