jobs:
  backend-test:
    executor: python-executor
    working_directory: ~/repo/backend
    steps:
      - checkout
      - run:
          name: List files for debug
          command: ls -al
      - run:
          name: Install Python dependencies
          command: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
      - run:
          name: Run Django tests
          command: python manage.py test

  frontend-test:
    executor: node-executor
    working_directory: ~/repo/frontend
    steps:
      - checkout
      - run:
          name: List files for debug
          command: ls -al
      - run:
          name: Install Node.js dependencies
          command: npm install
      - run:
          name: Run React tests
          command: npm test -- --watchAll=false
