version: 2.1

executors:
  python-executor:
    docker:
      - image: circleci/python:3.9
    working_directory: ~/repo
  node-executor:
    docker:
      - image: circleci/node:14
    working_directory: ~/repo

jobs:
  backend-test:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Install Python dependencies
          command: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
      - run:
          name: Run Django tests
          command: python manage.py test

  frontend-test:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Navigate to frontend directory
          command: cd frontend
      - run:
          name: List files in frontend directory
          command: ls -la
      - run:
          name: Install Node.js dependencies
          command: |
            cd frontend
            npm install
      - run:
          name: List files in src directory
          command: |
            cd frontend/src
            ls -la
      - run:
          name: Run React tests
          command: |
            cd frontend
            npm test -- --watchAll=false

workflows:
  version: 2.1
  build-and-test:
    jobs:
      - backend-test
      - frontend-test
