# Generated by Django 4.2 on 2023-08-04 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Taberu', '0002_alter_taberu_options_taberu_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taberu',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/uploaded/'),
        ),
    ]
