# Generated by Django 5.0.1 on 2024-06-08 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Taberu', '0004_taberu_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('atmosphere', models.CharField(max_length=255)),
                ('taste', models.CharField(max_length=255)),
                ('egg_texture', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
    ]
